import React,{useEffect,useMemo,useState} from 'react';
import {api} from '../services/api';
import {connectPipelineSocket} from '../services/socket';
import VirtualizedCsvPreview from '../components/VirtualizedCsvPreview';
import '../styles/Pipelines.css'; import '../styles/VirtualizedPreview.css';

const emptyMapping={source:'',destination:'',transform:'',required:false,validation:''};
const socketStatus={connecting:'CONNECTING',connected:'LIVE',disconnected:'OFFLINE'};

export default function PipelinesPage(){
 const [pipelines,setPipelines]=useState([]),[uploads,setUploads]=useState([]),[form,setForm]=useState({name:'',description:'',mappings:[{...emptyMapping}],batchSize:5000}),[jobId,setJobId]=useState(''),[preview,setPreview]=useState(null),[message,setMessage]=useState(''),[error,setError]=useState(''),[loading,setLoading]=useState(false),[running,setRunning]=useState(null),[socketState,setSocketState]=useState(socketStatus.connecting),[failedRows,setFailedRows]=useState([]);
 const selectedUpload=useMemo(()=>uploads.find(u=>u.jobId===jobId),[uploads,jobId]);
 const load=async()=>{try{const [p,u]=await Promise.all([api.get('/api/pipelines'),api.get('/api/etl/uploads')]);setPipelines(p.pipelines||[]);setUploads(u.uploads||[])}catch(e){setError(e.message)}};
 useEffect(()=>{load();const socket=connectPipelineSocket();socket.on('connect',()=>setSocketState(socketStatus.connected));socket.on('disconnect',()=>setSocketState(socketStatus.disconnected));return()=>socket.disconnect()},[]);
 useEffect(()=>{if(!jobId)return;let active=true;api.get(`/api/etl/uploads/${jobId}/preview?limit=1000`).then(d=>{if(active)setPreview(d)}).catch(e=>setError(e.message));return()=>{active=false}},[jobId]);
 useEffect(()=>{if(!running?.id)return;const socket=connectPipelineSocket();const event=`pipeline-run:${running.id}`;const onProgress=data=>{setRunning(r=>({...r,...data}));if(data.failedRow)setFailedRows(rows=>rows.length<500?[...rows,data.failedRow]:rows);if(data.status==='SUCCESS'||data.status==='FAILED')api.get(`/api/pipelines/${running.pipelineId||running.pipeline}/runs/${running.id}`).then(d=>{setRunning(d.run);setFailedRows(d.run.failedRows||[])})};socket.on(event,onProgress);const fallback=setTimeout(()=>api.get(`/api/pipelines/${running.pipelineId||running.pipeline}/runs/${running.id}`).then(d=>{setRunning(d.run);setFailedRows(d.run.failedRows||[])}).catch(()=>{}),3000);return()=>{clearTimeout(fallback);socket.off(event,onProgress);socket.disconnect()}},[running?.id]);
 const setField=(k,v)=>setForm(f=>({...f,[k]:v}));
 const setMap=(i,k,v)=>setForm(f=>({...f,mappings:f.mappings.map((m,idx)=>idx===i?{...m,[k]:v}:m)}));
 const applySource=(i,source)=>setForm(f=>({...f,mappings:f.mappings.map((m,idx)=>idx===i?{...m,source,destination:m.destination||source}:m)}));
 const save=async e=>{e.preventDefault();setError('');setMessage('');if(!form.name.trim())return setError('Pipeline name is required.');const mappings=form.mappings.filter(m=>m.source&&m.destination);if(!mappings.length)return setError('Add at least one source → destination mapping.');setLoading(true);try{await api.post('/api/pipelines',{name:form.name,description:form.description,mappings,batchSize:Number(form.batchSize),source:{type:'csv-upload'},destination:{type:'mongodb',collectionPrefix:'etl_'}});setMessage('Pipeline created successfully.');setForm({name:'',description:'',mappings:[{...emptyMapping}],batchSize:5000});load()}catch(e){setError(e.message)}finally{setLoading(false)}};
 const run=async p=>{setError('');setMessage('');if(!jobId.trim())return setError('Select an uploaded dataset/job before running.');try{const data=await api.post(`/api/pipelines/${p._id}/run`,{sourceJobId:jobId.trim()});setRunning(data.run);setFailedRows([]);setMessage(`Run ${data.run.id} started. Live progress is connected through WebSocket.`)}catch(e){setError(e.message)}};
 const del=async id=>{if(!confirm('Delete this pipeline?'))return;try{await api.delete(`/api/pipelines/${id}`);load()}catch(e){setError(e.message)}};
 return <div className="pipelines-page">
  <div className="pipeline-page-header"><div><h1>Pipeline Builder</h1><p>Create, map, validate and run MongoDB-backed streaming ETL pipelines.</p></div><span className={`socket-badge ${socketState.toLowerCase()}`}>● {socketState}</span></div>
  {message&&<div className="success-message">✓ {message}</div>}{error&&<div className="error-message">⚠ {error}</div>}
  <form className="pipeline-card" onSubmit={save}>
   <div className="section-title"><span className="section-number">1</span><div><h2>Pipeline Details</h2><p>Configure the source-to-destination mapping and validation rules.</p></div></div>
   <div className="form-grid"><div className="form-field"><label>Pipeline Name <span>*</span></label><input value={form.name} onChange={e=>setField('name',e.target.value)} placeholder="Customer Data Pipeline"/></div><div className="form-field"><label>Description</label><input value={form.description} onChange={e=>setField('description',e.target.value)} placeholder="Optional description"/></div></div>
   <div className="form-field batch-field"><label>MongoDB Bulk Batch Size</label><input type="number" min="1" max="10000" value={form.batchSize} onChange={e=>setField('batchSize',e.target.value)}/><span className="helper-text">Default is 5,000 records per bulkWrite operation.</span></div>
   <div className="visual-mapping-head"><div><label>Visual Column Mapping <span>*</span></label><p>Choose a CSV source column, map it to a MongoDB field, then optionally transform or validate it.</p></div></div>
   <div className="mapping-visual-header"><span>CSV SOURCE</span><span>FLOW</span><span>MONGODB DESTINATION</span><span>TRANSFORM / VALIDATION</span></div>
   <div className="mappings">{form.mappings.map((m,i)=><div className="mapping-row enhanced" key={i}>
      <select required value={m.source} onChange={e=>applySource(i,e.target.value)}><option value="">Select source column</option>{(preview?.columns||[]).map(c=><option key={c} value={c}>{c}</option>)}</select><span className="mapping-arrow">→</span>
      <input required placeholder="MongoDB field" value={m.destination} onChange={e=>setMap(i,'destination',e.target.value)}/>
      <div className="mapping-rules"><input placeholder="value => value.trim().toUpperCase()" value={m.transform} onChange={e=>setMap(i,'transform',e.target.value)}/><input placeholder="Validation regex e.g. /^[^@]+@[^@]+$/" value={m.validation} onChange={e=>setMap(i,'validation',e.target.value)}/><label className="required-toggle"><input type="checkbox" checked={Boolean(m.required)} onChange={e=>setMap(i,'required',e.target.checked)}/> Required</label></div>
      {form.mappings.length>1&&<button type="button" className="link small" onClick={()=>setForm(f=>({...f,mappings:f.mappings.filter((_,x)=>x!==i)}))}>✕</button>}
   </div>)}<button type="button" className="link small" onClick={()=>setForm(f=>({...f,mappings:[...f.mappings,{...emptyMapping}]}))}>+ Add mapping</button></div>
   {!preview&&<div className="helper-panel">Select an uploaded dataset below to load its real CSV headers into the visual mapper.</div>}
   <button className="pipeline-submit-btn" disabled={loading}>{loading?'Saving…':'Save Pipeline'}</button>
  </form>
  <div className="pipeline-card"><div className="section-title"><span className="section-number">2</span><div><h2>Source Preview & Run</h2><p>Preview the first 1,000 rows with virtualization before starting the ETL stream.</p></div></div>
    <div className="form-grid"><div className="form-field"><label>Uploaded Dataset</label><select value={jobId} onChange={e=>setJobId(e.target.value)}><option value="">Select dataset</option>{uploads.map(u=><option key={u.jobId} value={u.jobId}>{u.originalName} — {u.jobId.slice(0,8)}</option>)}</select></div><div className="form-field"><label>Preview status</label><input disabled value={preview?`${preview.rowCount} rows / ${preview.columns.length} columns (max 1,000)`:selectedUpload?'Loading preview…':'Select a dataset first'}/></div></div>
    {preview&&<div className="preview-wrap"><VirtualizedCsvPreview columns={preview.columns} rows={preview.rows} failedRows={failedRows}/></div>}
    {running&&<div className="live-monitor"><div className="live-monitor-head"><strong>Live ETL Progress</strong><span className={`run-status ${String(running.status).toLowerCase()}`}>{running.status}</span></div><div className="progress-track"><div className="progress-fill" data-live={running.status==='RUNNING'} style={{width:`${running.status==='RUNNING'?(running.percent||Math.min(95,Math.max(8,Math.round(((running.processedRows||0)+(running.failedRowCount||0))/60000*100)))):100}%`}}/></div><div className="progress-metrics"><span>Processed <b>{(running.processedRows||0).toLocaleString()}</b></span><span>Inserted <b>{(running.insertedRows||0).toLocaleString()}</b></span><span>Failed <b>{(running.failedRowCount||0).toLocaleString()}</b></span></div></div>}
    {running&&running.status!=='RUNNING'&&failedRows.length>0&&<div className="failed-rows-panel"><div><h3>Validation / Transformation Errors</h3><p>Failed rows are retained for inspection; successful rows continue through the stream.</p></div><VirtualizedCsvPreview columns={preview?.columns||Object.keys(failedRows[0]?.source||{})} rows={failedRows.map(x=>x.source)} failedRows={failedRows.map((x,i)=>({...x,rowNumber:i+1}))} height={300}/></div>}
  </div>
  <div className="pipeline-card"><div className="section-title"><span className="section-number">3</span><div><h2>Your Pipelines</h2><p>{pipelines.length} saved pipeline(s).</p></div></div>{pipelines.length===0?<p>No pipelines yet.</p>:pipelines.map(p=><div className="pipeline-list-item" key={p._id}><div><strong>{p.name}</strong><p>{p.description||'No description'} • {p.mappings?.length||0} mappings • batch {p.batchSize||5000}</p></div><div><button className="link small" onClick={()=>run(p)}>Run</button><button className="link small" onClick={()=>del(p._id)}>Delete</button></div></div>)}</div>
 </div>
}
